# The project .bit file produced by the Xilinx .xise project
PROJECT = opc5copro

# The target .bit file to be generated including the monitor program
TARGET  = opc5copro

# Xilinx cable specific - the prom type
PROM    = xcf01s

# Use the default CPU
CPU     = default

# Common include files
include ../../common/Makefile.inc
include ../../common/Makefile_xilinx_cable.inc
