VPATH=..:../../bcpl

ROOT= ../..

OPT ?= -o
ARCH ?= opc6
assembler ?= ../${ARCH}asm.py
emulator ?= ../${ARCH}emu.py


# include common BCPL routines for different CPUs
include $(ROOT)/bcpl/Makefile_bcpl.inc

