# The project .bit file produced by the Xilinx .xise project
PROJECT    = copro

# The target .bit file to be generated including the monitor program
TARGET     = copro

# Xilinx cable specific - the prom type
PROM       = xcf01s

# CPU Module Name
CPU_MODULE = opc5ls

# CPU File Path
CPU_PATH   = opc5ls/opc5lscpu.v

# Assembler File Path
ASM_PATH   = opc5ls/opc5lsasm.py

# Program Source Path
PROG_SRC   = ../../tuberom.s

# Common include files
include ../../../common/Makefile.inc
include ../../../common/Makefile_xilinx_cable.inc
