# The project .bit file produced by the Xilinx .xise project
PROJECT = opc5system

# The target .bit file to be generated including the monitor program
TARGET  = opc5system

# Papilio cable specific - location of programmer bscan file
BSCAN   = ../../common/bscan_spi_xc3s500e.bit

# Use the xp flavour CPU
CPU     = xp

# Common include files
include ../../common/Makefile.inc
include ../../common/Makefile_papilio_cable.inc
