#!/bin/bash
#
# Basic commands to synthesize and fit verilog into an FPGA without using the ISE.
#
# Clean up first

# code project name here temporarily
project_name="opccpu"
target="xc3s500e-pq208-5"

# Clean up so only primary data remains
rm -rf *~ xst .#* `ls -1 | egrep -v '(prj|xst|README)$'`

# Create new work directories
mkdir tmp
mkdir xst 

echo "work" > $project_name.lso

# Synthesis
xst \
    -ifn "./${project_name}.xst" \
    -intstyle xflow              \
    -ofn "./${project_name}.syr" 
#
ngdbuild    -dd _ngo  \
	    -p  $target \
	    -uc ../${project_name}.ucf \
	    ${project_name}.ngc \
	    ${project_name}.ngd  

# map then place and route the selected device
map -p $target \
    -cm area -ir off -pr off -c 100 \
    -o ${project_name}_map.ncd \
    ${project_name}.ngd \
    ${project_name}.pcf
par -w \
    -ol std \
    -t 1 \
    ${project_name}_map.ncd \
    ${project_name}.ncd \
    ${project_name}.pcf

# Run the TA engine and generate reports
trce -v 3 \
     -s 5 \
     -fastpaths \
     -xml ${project_name}.twx ${project_name}.ncd \
     -o ${project_name}.twr ${project_name}.pcf

# Generate the JEDEC file for programming
bitgen \
  -w			      \
  -g DebugBitstream:No	      \
  -g Binary:no		      \
  -g CRC:Enable		      \
  -g ConfigRate:6	      \
  -g CclkPin:PullUp	      \
  -g M0Pin:PullUp	      \
  -g M1Pin:PullUp	      \
  -g M2Pin:PullUp	      \
  -g ProgPin:PullUp	      \
  -g DonePin:PullUp	      \
  -g TckPin:PullUp	      \
  -g TdiPin:PullUp	      \
  -g TdoPin:PullUp	      \
  -g TmsPin:PullUp	      \
  -g UnusedPin:PullDown	      \
  -g UserID:0xFFFFFFFF	      \
  -g DCMShutdown:Disable      \
  -g DCIUpdateMode:AsRequired \
  -g StartUpClk:CClk	      \
  -g DONE_cycle:4	      \
  -g GTS_cycle:5	      \
  -g GWE_cycle:6	      \
  -g LCK_cycle:NoWait	      \
  -g Match_cycle:Auto	      \
  -g Security:None	      \
  -g DonePipe:No	      \
  -g DriveDone:No             \
  ${project_name}.ncd

# dump a verilog netlist - something like this,..
netgen -w -ofmt verilog  -aka ${project_name}_map.ncd
