# The project .bit file produced by the Xilinx .xise project
PROJECT = opc5wrapper

# The target .bit file to be generated including the monitor program
TARGET  = opc5system

# Xilinx cable specific - the prom type
PROM    = N25Q128

# Use the xp flavour CPU
CPU     = xp

# Common include files
include ../../common/Makefile.inc
include ../../common/Makefile_xilinx_cable.inc
